array_width = 80
attr_fn_like_width = 80
chain_width = 80
edition = "2018"
fn_call_width = 80
fn_cell_width = 80
ignore = [
# "src/some_file.rs",
]
match_block_trailing_comma = true
max_width = 80
reorder_imports = true
single_line_if_else_max_width = 80
struct_lit_width = 80
struct_variant_width = 80
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true